dataset:
    dataset_name: "squad"
model_config:
    checkpoint: "distilbert-base-uncased" # HF hub model card
training_config:
    output_dir: './results/qa_results'
    learning_rate: 5.0e-5
    evaluation_strategy: "epoch"
    logging_strategy: "epoch"
    save_strategy: "epoch"
    save_total_limit: 1
    per_device_train_batch_size: 8 # batch_size
    per_device_eval_batch_size: 8 # batch_size